// GENERATED by scripts/sync-permissions.mjs — do not edit.
// Source: the backend's docs/contracts/permission-manifest.json, itself generated from every
// @PreAuthorize gate. A code here is enforced by at least one endpoint.

/** Every permission code the backend actually enforces. */
export const PERMISSION_CODES = [
  'ASSETS_MANAGE', // 7 endpoint(s)
  'ASSETS_VIEW', // 10 endpoint(s)
  'BRANCHES_CREATE', // 1 endpoint(s)
  'BRANCHES_UPDATE', // 2 endpoint(s)
  'BRANCHES_VIEW', // 2 endpoint(s)
  'DEVICES_MANAGE', // 3 endpoint(s)
  'EXPENSES_CATEGORY_MANAGE', // 4 endpoint(s)
  'EXPENSES_CREATE', // 2 endpoint(s)
  'EXPENSES_VIEW', // 3 endpoint(s)
  'EXPENSES_VOID', // 1 endpoint(s)
  'HR_EMPLOYEES_CREATE', // 1 endpoint(s)
  'HR_EMPLOYEES_UPDATE', // 2 endpoint(s)
  'HR_EMPLOYEES_VIEW', // 2 endpoint(s)
  'HR_LEAVES_VIEW', // 2 endpoint(s)
  'HR_LEAVE_BALANCES_MANAGE', // 2 endpoint(s)
  'HR_LEAVE_BALANCES_VIEW', // 1 endpoint(s)
  'HR_LEAVE_REQUESTS_MANAGE', // 4 endpoint(s)
  'HR_LEAVE_REQUESTS_VIEW', // 3 endpoint(s)
  'HR_LEAVE_TYPES_MANAGE', // 3 endpoint(s)
  'HR_SALARIES_MANAGE', // 1 endpoint(s)
  'HR_SALARIES_VIEW', // 2 endpoint(s)
  'HR_SALARY_ADJUSTMENTS_MANAGE', // 2 endpoint(s)
  'HR_SALARY_ADJUSTMENTS_VIEW', // 1 endpoint(s)
  'INVENTORY_PURCHASE_MANAGE', // 16 endpoint(s)
  'INVENTORY_PURCHASE_VIEW', // 6 endpoint(s)
  'INVENTORY_REPORTS_VIEW', // 6 endpoint(s)
  'INVENTORY_SETUP_MANAGE', // 20 endpoint(s)
  'INVENTORY_SETUP_VIEW', // 12 endpoint(s)
  'INVENTORY_STOCK_MANAGE', // 21 endpoint(s)
  'INVENTORY_STOCK_VIEW', // 8 endpoint(s)
  'JOBS_CREATE', // 1 endpoint(s)
  'JOBS_UPDATE', // 2 endpoint(s)
  'JOBS_VIEW', // 2 endpoint(s)
  'LOYALTY_MANAGE', // 1 endpoint(s)
  'LOYALTY_VIEW', // 1 endpoint(s)
  'ORDERS_CREATE', // 5 endpoint(s)
  'ORDERS_VIEW', // 4 endpoint(s)
  'PERMISSIONS_VIEW', // 2 endpoint(s)
  'PHYSICAL_COUNT_DELETE', // 1 endpoint(s)
  'PHYSICAL_COUNT_REVERT_TO_DRAFT', // 1 endpoint(s)
  'PRODUCTS_CHANGE_STATUS', // 1 endpoint(s)
  'PRODUCTS_CREATE', // 2 endpoint(s)
  'PRODUCTS_DELETE', // 1 endpoint(s)
  'PRODUCTS_UPDATE', // 6 endpoint(s)
  'PRODUCTS_VIEW', // 10 endpoint(s)
  'PURCHASE_INVOICE_DELETE', // 1 endpoint(s)
  'PURCHASE_INVOICE_UNCOMPLETE', // 1 endpoint(s)
  'PURCHASE_INVOICE_UNPOST', // 1 endpoint(s)
  'PURCHASE_RETURN_DELETE', // 1 endpoint(s)
  'PURCHASE_RETURN_UNCOMPLETE', // 1 endpoint(s)
  'PURCHASE_RETURN_UNPOST', // 1 endpoint(s)
  'REPORTS_VIEW_SALES', // 4 endpoint(s)
  'SHIFTS_CLOSE', // 1 endpoint(s)
  'SHIFTS_FORCE_CLOSE', // 1 endpoint(s)
  'SHIFTS_OPEN', // 1 endpoint(s)
  'SHIFTS_VIEW', // 3 endpoint(s)
  'TABLES_MANAGE', // 11 endpoint(s)
  'TABLES_VIEW', // 4 endpoint(s)
  'USERS_CHANGE_STATUS', // 1 endpoint(s)
  'USERS_CREATE', // 1 endpoint(s)
  'USERS_DELETE', // 1 endpoint(s)
  'USERS_UPDATE', // 1 endpoint(s)
  'USERS_VIEW', // 2 endpoint(s)
  'USER_PERMISSIONS_UPDATE', // 2 endpoint(s)
  'WASTE_UNCOMPLETE', // 1 endpoint(s)
] as const

export type PermissionCode = (typeof PERMISSION_CODES)[number]

/**
 * Role rules the backend gates on directly, instead of a permission. These cannot be granted to a
 * user — they are a property of the role, so the UI must check `roleCode`, not `permissions`.
 */
export const ROLE_RULES = {
  isSysAdmin: 'isSysAdmin',
} as const

export type RoleRule = keyof typeof ROLE_RULES
