import {
  Boxes,
  Briefcase,
  BriefcaseBusiness,
  Building2,
  Calculator,
  ChartBar,
  Clock,
  Grid2x2,
  Heart,
  KeyRound,
  LayoutDashboard,
  Monitor,
  Package,
  ReceiptText,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingCart,
  Tags,
  UserRound,
  UsersRound,
  Warehouse,
  type LucideIcon,
} from 'lucide-react'

const MODULE_ICONS: Record<string, LucideIcon> = {
  ACCOUNTING: Calculator,
  ASSETS: Package,
  BRANCHES: Building2,
  CATEGORIES: Tags,
  CUSTOMERS: UserRound,
  DASHBOARD: LayoutDashboard,
  DEVICES: Monitor,
  EMPLOYEES: UsersRound,
  HR: BriefcaseBusiness,
  INVENTORY: Warehouse,
  JOBS: Briefcase,
  LOYALTY: Heart,
  MATERIALS: Boxes,
  ORDERS: ReceiptText,
  PERMISSIONS: KeyRound,
  POS: ShoppingCart,
  PRODUCTS: Package,
  REPORTS: ChartBar,
  ROLES: Shield,
  SETTINGS: Settings,
  SHIFTS: Clock,
  TABLES: Grid2x2,
  USERS: UsersRound,
}

export function getPermissionModuleIcon(module: string): LucideIcon {
  return MODULE_ICONS[module.toUpperCase()] ?? ShieldCheck
}
